import { describe, expect, it } from "vitest";
import * as db from "@/lib/data/db";

/**
 * What `@/lib/data/db` offers the rest of the app.
 *
 * B2 turned that file into a barrel over `db/`, and a barrel of `export *` has
 * one failure mode worth guarding: a helper that was private inside the old
 * 4,000-line file becomes public the moment a sibling needs it, and nothing
 * says so. The other direction is worse — a name dropped from a re-export is a
 * compile error at every call site, which is loud, but a name *moved* between
 * files and accidentally left un-exported is not.
 *
 * So the surface is pinned. When this snapshot changes, the question is which
 * of the two happened:
 *
 *   - a name **added**: is it meant to be reachable from outside `src/lib/data`,
 *     or is it plumbing between two files under `db/` that should have gone in
 *     `db/core.ts` instead — which the barrel deliberately does not re-export?
 *   - a name **removed**: every caller is already broken, so this is just the
 *     record catching up. Accept it.
 *
 * Only runtime values are visible here — `Object.keys` cannot see an exported
 * interface or type alias, so those are not listed and are not guarded. That is
 * the smaller half: a type that goes missing is a compile error everywhere it
 * was used, while a *value* quietly gaining reach is silent.
 *
 * `src/lib/auth/enforcement.test.ts` and A5's lint rule decide *who* may import
 * this module. This decides what there is to import.
 */

describe("the data layer's public surface", () => {
  it("is the list that is written down", async () => {
    const names = Object.keys(db).sort();
    const lines = [
      "# What `@/lib/data/db` exports",
      "",
      "Generated by `src/lib/data/db-surface.test.ts`. See that file for what a",
      "change here means.",
      "",
      ...names.map((n) => `- ${n}`),
      "",
    ];
    await expect(lines.join("\n")).toMatchFileSnapshot("./__snapshots__/db-surface.md");
  });

  it("keeps the row helpers out of it", () => {
    // `Row` and `opt` are how this layer reads a SQLite row — a column is
    // `null`, never `undefined`, and everything above wants the opposite. They
    // live in `db/core.ts`, which the barrel re-exports three names from and no
    // more, and there is nothing above this directory they could mean anything
    // to.
    expect(Object.keys(db)).not.toContain("opt");
    expect(Object.keys(db)).not.toContain("Row");
  });
});
